language: php

dist: xenial

git:
    depth: 2

cache:
  directories:
    - $HOME/.composer/cache
env:
  global:
    - SYMFONY_PHPUNIT_DISABLE_RESULT_CACHE=1

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env: SYMFONY_VERSION=4.4.*
    - php: 7.4
      env: SYMFONY_VERSION=4.4.*
    - php: 8.0
      env: SYMFONY_VERSION=4.4.*

    - php: 7.3
      env: SYMFONY_VERSION=5.2.*
    - php: 7.4
      env: SYMFONY_VERSION=5.2.*
    - php: 8.0
      env:
        - SYMFONY_VERSION=5.2.*
        - COMPOSER_FLAGS="--optimize-autoloader"
        - COVERAGE=true
        - XDEBUG_MODE=coverage
        - PHPUNIT_FLAGS="--coverage-clover build/logs/clover.xml"

before_install:
  - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - |  # Enable extra update
    if [[ $COVERAGE = true ]]; then
      composer req php-coveralls/php-coveralls phpunit/phpcov --dev
    fi

install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}"; fi;
  - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
  - composer test install

script:
  - composer validate --strict --no-check-lock
  - composer test -- $PHPUNIT_FLAGS

after_success:
  - if [[ $COVERAGE = true ]]; then vendor/bin/php-coveralls -v --exclude-no-stmt; fi;
