language: php

dist: trusty

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env: SYMFONY_VERSION=4.4.*
    - php: 7.4
      env: SYMFONY_VERSION=5.2.*

    - php: nightly
      env: SYMFONY_VERSION=4.4.*
    - php: nightly
      env: SYMFONY_VERSION=5.2.*

before_install:
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
  - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;

install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}"; fi;
  - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
  - composer test install

script:
  - composer validate --strict --no-check-lock
  - composer test -- $PHPUNIT_FLAGS
