services:
    Raneomik\WatchdogBundle\Watchdog\Watchdog:
        public: true
        arguments:
            $watchdogParameters: '%watchdog_config%'

    _instanceof:
        Raneomik\WatchdogBundle\Handler\WatchdogHandlerInterface:
            tags: [raneomik_watchdog.handler]

    Raneomik\WatchdogBundle\Subscriber\WatchdogSubscriber:
        arguments:
            $watchdog: '@Raneomik\WatchdogBundle\Watchdog\Watchdog'
            $watchdogHandlers: !tagged raneomik_watchdog.handler
        tags: [kernel.event_subscriber]
